### ISSUE TITLE
Версия node.js 10

### ISSUE THREAD

**Issue by petrgrishin** [CheerlessCloud/koa-node8-boilerplate#5]
А почему у вас в названии репозитория node8, а по факту `FROM node:10.12-alpine`?

**Comment by Goodluckhf** [comment]
> А почему у вас в названии репозитория node8, а по факту `FROM node:10.12-alpine`?

Ой есть ветка v8 https://github.com/CheerlessCloud/koa-node8-boilerplate/tree/v8

**Comment by CheerlessCloud** [comment]
Так исторически сложилось (с)
